// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9E1Xi_OWvasFclQKuRCsOWHmzMX-85Q',
    appId: '1:118627342016:web:4885cdcf89d93e7b797f25',
    messagingSenderId: '118627342016',
    projectId: 'eaid-491da',
    authDomain: 'eaid-491da.firebaseapp.com',
    databaseURL: 'https://eaid-491da-default-rtdb.firebaseio.com',
    storageBucket: 'eaid-491da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrpOEkVcZAFm0y8r3hDiYpWdFmAqrR1I',
    appId: '1:118627342016:android:a9c5cb33cc657a54797f25',
    messagingSenderId: '118627342016',
    projectId: 'eaid-491da',
    databaseURL: 'https://eaid-491da-default-rtdb.firebaseio.com',
    storageBucket: 'eaid-491da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS68UK4SIMdIAsH7RsGSCGBOIFtFBXSdM',
    appId: '1:118627342016:ios:13d704ffdb6b238f797f25',
    messagingSenderId: '118627342016',
    projectId: 'eaid-491da',
    databaseURL: 'https://eaid-491da-default-rtdb.firebaseio.com',
    storageBucket: 'eaid-491da.appspot.com',
    iosClientId: '118627342016-gtg0ueq1rl87fvlsv7993omq5puemue3.apps.googleusercontent.com',
    iosBundleId: 'com.ug.eaid.android',
  );
}
